-- Sample Events Data
-- Description: Insert queries for Zamana and Atrangi Raas 2024 events

-- Insert Zamana Event
INSERT INTO events (
    id,
    title,
    slug,
    description,
    start_date,
    end_date,
    ticket_sales_open,
    ticket_sales_close,
    venue_name,
    venue_address,
    venue_city,
    venue_province,
    venue_postal_code,
    venue_country,
    total_capacity,
    total_tickets_sold,
    currency,
    total_revenue,
    ticket_tiers,
    num_sponsors,
    num_volunteers,
    banner_image,
    thumbnail_image,
    gallery_images,
    status,
    is_featured,
    is_public,
    meta_title,
    meta_description,
    tags,
    created_at,
    updated_at
) VALUES (
    '550e8400-e29b-41d4-a716-446655440001',
    'Zamana',
    'zamana-2025',
    'Experience an unforgettable night of Bollywood music featuring live performances, DJ sets, and dancing. Join us for a celebration of Indian culture and music.',
    '2025-05-23 21:00:00-04',
    '2025-05-24 01:00:00-04',
    '2025-03-15 00:00:00-04',
    '2025-05-22 23:59:00-04',
    'The Vue',
    '195 Galaxy Blvd',
    'Etobicoke',
    'Ontario',
    'M9W 6R7',
    'Canada',
    400,
    350,
    'CAD',
    7000.00,
    '[
        {
            "name": "Early Bird",
            "price": 15.00,
            "capacity": 100,
            "sold": 100,
            "available_until": "2025-04-01T00:00:00Z"
        },
        {
            "name": "Tier 1",
            "price": 20.00,
            "capacity": 150,
            "sold": 150,
            "available_until": "2025-05-01T00:00:00Z"
        },
        {
            "name": "Tier 2",
            "price": 25.00,
            "capacity": 150,
            "sold": 100,
            "available_until": null
        }
    ]'::jsonb,
    9,
    40,
    '/images/events/zamana-banner.jpg',
    '/images/events/zamana-thumb.jpg',
    '["/images/events/zamana-1.jpg", "/images/events/zamana-2.jpg", "/images/events/zamana-3.jpg"]'::jsonb,
    'completed',
    false,
    true,
    'Zamana - Bollywood Night in London, ON | Atrangi Eventz',
    'Join us for Zamana, a spectacular Bollywood music night featuring live performances and DJ sets in London, Ontario.',
    ARRAY['bollywood', 'music', 'dance', 'nightlife', 'cultural'],
    '2025-03-01 10:00:00-05',
    '2025-05-24 09:30:00-04'
);

-- Insert Atrangi Raas 2024 Event
INSERT INTO events (
    id,
    title,
    slug,
    description,
    start_date,
    end_date,
    ticket_sales_open,
    ticket_sales_close,
    venue_name,
    venue_address,
    venue_city,
    venue_province,
    venue_postal_code,
    venue_country,
    total_capacity,
    total_tickets_sold,
    currency,
    total_revenue,
    ticket_tiers,
    num_sponsors,
    num_volunteers,
    banner_image,
    thumbnail_image,
    gallery_images,
    status,
    is_featured,
    is_public,
    meta_title,
    meta_description,
    tags,
    created_at,
    updated_at
) VALUES (
    '550e8400-e29b-41d4-a716-446655440002',
    'Atrangi Raas 2024',
    'atrangi-raas-2024',
    'Join us for the biggest Garba and Raas Dandiya celebration in London! Experience traditional Gujarati folk dance with live music, authentic food, and vibrant celebrations during Navratri.',
    '2024-08-24 17:30:00-04',
    '2024-08-24 23:30:00-04',
    '2024-06-15 00:00:00-04',
    '2024-08-23 23:59:00-04',
    'Century Gardens',
    '340 Vodden St E',
    'Brampton',
    'Ontario',
    'L6V 2N2',
    'Canada',
    400,
    400,
    'CAD',
    8850.00,
    '[
        {
            "name": "Early Bird",
            "price": 18.00,
            "capacity": 100,
            "sold": 100,
            "available_until": "2024-07-15T00:00:00Z"
        },
        {
            "name": "Tier 1",
            "price": 22.00,
            "capacity": 150,
            "sold": 150,
            "available_until": "2024-08-01T00:00:00Z"
        },
        {
            "name": "Tier 2",
            "price": 25.00,
            "capacity": 150,
            "sold": 150,
            "available_until": null
        }
    ]'::jsonb,
    9,
    30,
    '/images/events/atrangi-raas-2024-banner.jpg',
    '/images/events/atrangi-raas-2024-thumb.jpg',
    '["/images/events/raas-1.jpg", "/images/events/raas-2.jpg", "/images/events/raas-3.jpg", "/images/events/raas-4.jpg"]'::jsonb,
    'completed',
    true,
    true,
    'Atrangi Raas 2024 - Garba & Dandiya Night | Atrangi Eventz',
    'Experience the grandest Garba and Raas Dandiya celebration in London, Ontario. Traditional music, dance, and authentic festivities for Navratri 2024.',
    ARRAY['garba', 'raas', 'dandiya', 'navratri', 'gujarati', 'cultural', 'traditional'],
    '2024-06-01 14:00:00-04',
    '2024-08-25 10:15:00-04'
);

-- Insert Test Event
INSERT INTO events (
    id,
    title,
    slug,
    description,
    start_date,
    end_date,
    ticket_sales_open,
    ticket_sales_close,
    venue_name,
    venue_address,
    venue_city,
    venue_province,
    venue_postal_code,
    venue_country,
    total_capacity,
    total_tickets_sold,
    currency,
    total_revenue,
    ticket_tiers,
    num_sponsors,
    num_volunteers,
    banner_image,
    thumbnail_image,
    gallery_images,
    status,
    is_featured,
    is_public,
    meta_title,
    meta_description,
    tags,
    created_at,
    updated_at
) VALUES (
    '550e8400-e29b-41d4-a716-446655440003',
    'Test Event',
    'test-event',
    'A test event to verify the event system functionality. Join us for an evening of testing and validation.',
    '2026-01-15 20:00:00-05',
    '2026-01-16 01:00:00-05',
    '2025-12-01 00:00:00-05',
    '2026-01-14 23:59:00-05',
    'Test Venue',
    '123 Test Street',
    'Toronto',
    'Ontario',
    'M5H 2N2',
    'Canada',
    200,
    50,
    'CAD',
    1000.00,
    '[
        {
            "name": "Early Bird",
            "price": 15.00,
            "capacity": 50,
            "sold": 20,
            "available_until": "2025-12-31T00:00:00Z"
        },
        {
            "name": "General Admission",
            "price": 20.00,
            "capacity": 150,
            "sold": 30,
            "available_until": null
        }
    ]'::jsonb,
    3,
    10,
    '/images/events/test-event-banner.jpg',
    '/images/events/test-event-thumb.jpg',
    '["/images/events/test-1.jpg", "/images/events/test-2.jpg"]'::jsonb,
    'published',
    false,
    true,
    'Test Event - January 2026 | Atrangi Eventz',
    'Join us for a test event in January 2026 to experience our event management system.',
    ARRAY['test', 'event', 'validation'],
    '2025-11-15 10:00:00-05',
    '2025-11-15 10:00:00-05'
);

-- Verify inserted data
SELECT
    id,
    title,
    slug,
    start_date,
    total_capacity,
    total_tickets_sold,
    tickets_remaining,
    is_sold_out,
    status
FROM events
WHERE slug IN ('zamana-2025', 'atrangi-raas-2024', 'test-event')
ORDER BY start_date;
